---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tubesyncs.controllers.illallangi.enterprises
spec:
  group: controllers.illallangi.enterprises
  names:
    kind: TubeSync
    plural: tubesyncs
    singular: tubesync
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Age of the instance
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: The Host Name of the instance
      jsonPath: .spec.hostName
      name: HostName
      type: string
    - description: The Domain Name to host the instance under
      jsonPath: .spec.domainName
      name: DomainName
      type: string
    - description: The URI Path to host the instance under
      jsonPath: .spec.uriPath
      name: URIPath
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          spec:
            properties:
              backup:
                properties:
                  claimName:
                    type: string
                  subPath:
                    default: ''
                    type: string
                required:
                - claimName
                type: object
              cert:
                properties:
                  issuerKind:
                    pattern: ^(((Cluster)?Issuer)|)$
                    type: string
                  issuerName:
                    type: string
                  organization:
                    type: string
                required:
                - issuerKind
                - issuerName
                - organization
                type: object
              data:
                properties:
                  claimName:
                    type: string
                  subPath:
                    default: ''
                    type: string
                required:
                - claimName
                type: object
              domainName:
                type: string
              hostName:
                type: string
              persistence:
                properties:
                  storage:
                    default: 128Gi
                    type: string
                  storageClassName:
                    type: string
                required:
                - storageClassName
                type: object
              uriPath:
                type: string
            required:
            - backup
            - cert
            - data
            - domainName
            - hostName
            - persistence
            - uriPath
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
