---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: tubesync
  name: tubesync-controller
  namespace: compute-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: tubesync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: tubesync
    spec:
      containers:
      - image: illallangi/tubesync-controller:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        name: controller
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
      serviceAccount: tubesync-controller
      serviceAccountName: tubesync-controller

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: tubesync
  name: tubesync-controller
  namespace: compute-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: tubesync
  name: tubesync-controller
rules:
- apiGroups:
  - controllers.illallangi.enterprises
  resources:
  - tubesyncs
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - controllers.illallangi.enterprises
  resources:
  - dnsrpzrecords
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - bind
  - escalate
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: tubesync
  name: tubesync-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tubesync-controller
subjects:
- kind: ServiceAccount
  name: tubesync-controller
  namespace: compute-system